# Generated by Django 2.2.2 on 2023-03-10 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('price', models.CharField(max_length=20)),
                ('image_url', models.CharField(max_length=200)),
                ('product_url', models.CharField(max_length=100)),
            ],
        ),
    ]
