# Generated by Django 2.2.2 on 2023-03-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_savedproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedproduct',
            name='product_id',
            field=models.CharField(default='swedrfgrt', max_length=30),
        ),
    ]
