# Generated by Django 2.2.2 on 2023-03-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_savedproduct_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedproduct',
            name='product_id',
            field=models.CharField(max_length=30),
        ),
    ]
