# Generated by Django 2.2.2 on 2023-03-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_savedproduct_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedproduct',
            name='vendor',
            field=models.CharField(choices=[('Jumia', 'Jumia'), ('Konga', 'Konga'), ('Unknown', 'Unknown')], default='Unknown', max_length=50),
        ),
    ]
