# Generated by Django 2.2.2 on 2023-03-16 18:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_savedproduct_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedproduct',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
